version: "3"

services:
  summerjob-web:
    container_name: summerjob-web
    hostname: summerjob-web
    image: summerjob/web
    restart: unless-stopped
    networks:
      - summerjob-network
      # - additional networks for reverse proxy or specify open ports below
    ports:
      - 3000:3000
    depends_on:
      - summerjob-db
      - summerjob-amqp

  summerjob-db:
    container_name: summerjob-db
    hostname: summerjob-db
    image: postgres:15
    environment:
      - POSTGRES_USER=myusername
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=summerjob
    networks:
      - summerjob-network
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: unless-stopped

  summerjob-planner:
    container_name: summerjob-planner
    hostname: summerjob-planner
    image: summerjob/planner
    restart: on-failure:5
    environment:
      - AMQP_URL=amqp://summerjob-amqp
      - QUEUE_NAME=planner
      - DATABASE_URL=postgresql://myusername:mypassword@summerjob-db:5432/summerjob?schema=public
    networks:
      - summerjob-network
    depends_on:
      - summerjob-db
      - summerjob-amqp

  summerjob-amqp:
    container_name: summerjob-amqp
    hostname: summerjob-amqp
    image: rabbitmq:3.11-management
    restart: unless-stopped
    networks:
      - summerjob-network

networks:
  summerjob-network:
    external: true

volumes:
  postgres:
