name: Check valid code

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint-web:
    name: Lint web
    strategy:
      matrix:
        node-version: [18]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run lint
  lint-planner:
    name: Lint planner
    strategy:
      matrix:
        node-version: [18]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./planner
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run lint
  build-web:
    name: Build web
    strategy:
      matrix:
        node-version: [18]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./web
          platforms: linux/amd64,linux/arm64/v8
          push: false

  # build-planner:
  #   name: Build planner
  #   strategy:
  #     matrix:
  #       node-version: [16, 18]
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: ./planner
  #   steps:
  #     - name: Check out code
  #       uses: actions/checkout@v3

  #     - name: Setup node
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ matrix.node-version }}

  #     - name: Install dependencies
  #       run: npm ci

  #     - name: Run tests
  #       run: npm run build
